"""Adicionar tabelas de veiculos

Revision ID: 0ec02466251a
Revises: d2b9d9c7255e
Create Date: 2025-05-29 17:20:46.293386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec02466251a'
down_revision = 'd2b9d9c7255e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_veiculo',
    sa.Column('id_categoria_veiculo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria_veiculo')
    )
    op.create_table('veiculo',
    sa.Column('id_veiculo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('placa', sa.String(), nullable=True),
    sa.Column('cor', sa.String(), nullable=True),
    sa.Column('combustivel', sa.String(), nullable=True),
    sa.Column('capacidade_passageiros', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('id_categoria_veiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_veiculo'], ['categoria_veiculo.id_categoria_veiculo'], ),
    sa.PrimaryKeyConstraint('id_veiculo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculo')
    op.drop_table('categoria_veiculo')
    # ### end Alembic commands ###
