"""Adicionar tabela fluxo_caixa

Revision ID: 1857b0069e89
Revises: 8fcd83687262
Create Date: 2025-10-02 16:27:58.636944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1857b0069e89'
down_revision = '8fcd83687262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fluxo_caixa',
    sa.Column('id_fluxo_caixa', sa.Integer(), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('saldo_inicial', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_fluxo_caixa'),
    sa.UniqueConstraint('data_referencia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fluxo_caixa')
    # ### end Alembic commands ###
