"""Adicionar campo telefone_contato ao modelo Circo

Revision ID: 2532bdcd1126
Revises: 0ec02466251a
Create Date: 2025-05-31 17:41:08.194316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2532bdcd1126'
down_revision = '0ec02466251a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circo', sa.Column('telefone_contato', sa.String(), nullable=True))

    # Atualizar registros existentes com valor padrão "0"
    op.execute("UPDATE circo SET telefone_contato = '0' WHERE telefone_contato IS NULL")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circo', 'telefone_contato')
    # ### end Alembic commands ###
