"""adicionar_flags_alimentacao_combustivel_categoria_despesa

Revision ID: 7805fad20a8a
Revises: criar_tabela_veiculos_evento
Create Date: 2025-07-14 22:50:12.585836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7805fad20a8a'
down_revision = 'criar_tabela_veiculos_evento'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_alimentacao', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('flag_combustivel', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesa', schema=None) as batch_op:
        batch_op.drop_column('flag_combustivel')
        batch_op.drop_column('flag_alimentacao')
    # ### end Alembic commands ###
