"""Create colaborador_categoria table

Revision ID: 846c2ce7fe86
Revises: 2532bdcd1126
Create Date: 2025-06-01 14:05:04.519652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846c2ce7fe86'
down_revision = '2532bdcd1126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colaborador_categoria',
    sa.Column('id_colaborador_categoria', sa.Integer(), nullable=False),
    sa.Column('id_colaborador', sa.Integer(), nullable=False),
    sa.Column('id_categoria_colaborador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria_colaborador'], ['categoria_colaborador.id_categoria_colaborador'], ),
    sa.ForeignKeyConstraint(['id_colaborador'], ['colaborador.id_colaborador'], ),
    sa.PrimaryKeyConstraint('id_colaborador_categoria')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colaborador_categoria')
    # ### end Alembic commands ### 