"""adicionar campo comprovante na tabela despesas_evento

Revision ID: adicionar_comprovante
Revises: d2b9d9c7255e
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adicionar_comprovante'
down_revision = 'd2b9d9c7255e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('despesas_evento', sa.Column('comprovante', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('despesas_evento', 'comprovante')
    # ### end Alembic commands ### 