"""adicionar campo media_km_litro na tabela veiculo

Revision ID: adicionar_campo_media_km_litro_veiculo  
Revises: criar_tabela_parametros
Create Date: 2024-12-19 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adicionar_campo_media_km_litro_veiculo'
down_revision = 'criar_tabela_parametros'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('veiculo', sa.Column('media_km_litro', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veiculo', 'media_km_litro')
    # ### end Alembic commands ### 