"""adicionar tabelas despesa_empresa e receita_empresa

Revision ID: adicionar_tabelas_empresa
Revises: criar_tabela_veiculos_evento
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adicionar_tabelas_empresa'
down_revision = 'criar_tabela_veiculos_evento'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Criar tabela despesas_empresa
    op.create_table('despesas_empresa',
    sa.Column('id_despesa_empresa', sa.Integer(), nullable=False),
    sa.Column('id_despesa', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('id_fornecedor', sa.Integer(), nullable=True),
    sa.Column('status_pagamento', sa.String(length=20), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=False),
    sa.Column('pago_por', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('comprovante', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_despesa'], ['despesa.id_despesa'], ),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedor.id_fornecedor'], ),
    sa.PrimaryKeyConstraint('id_despesa_empresa')
    )
    
    # Criar tabela receitas_empresa
    op.create_table('receitas_empresa',
    sa.Column('id_receita_empresa', sa.Integer(), nullable=False),
    sa.Column('id_receita', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_receita'], ['receita.id_receita'], ),
    sa.PrimaryKeyConstraint('id_receita_empresa')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receitas_empresa')
    op.drop_table('despesas_empresa')
    # ### end Alembic commands ### 