"""alterar campo data para data_vencimento e adicionar data_pagamento

Revision ID: alterar_campo_data_para_vencimento_pagamento
Revises: adicionar_tabelas_empresa
Create Date: 2024-12-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'alterar_campo_data_para_vencimento_pagamento'
down_revision = 'adicionar_tabelas_empresa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Alterar tabela despesas_evento
    # 1. Renomear coluna 'data' para 'data_vencimento'
    op.alter_column('despesas_evento', 'data', new_column_name='data_vencimento')
    
    # 2. Adicionar nova coluna 'data_pagamento' (opcional)
    op.add_column('despesas_evento', sa.Column('data_pagamento', sa.Date(), nullable=True))
    
    # Alterar tabela despesas_empresa  
    # 1. Renomear coluna 'data' para 'data_vencimento'
    op.alter_column('despesas_empresa', 'data', new_column_name='data_vencimento')
    
    # 2. Adicionar nova coluna 'data_pagamento' (opcional)
    op.add_column('despesas_empresa', sa.Column('data_pagamento', sa.Date(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Reverter alterações na tabela despesas_empresa
    op.drop_column('despesas_empresa', 'data_pagamento')
    op.alter_column('despesas_empresa', 'data_vencimento', new_column_name='data')
    
    # Reverter alterações na tabela despesas_evento
    op.drop_column('despesas_evento', 'data_pagamento')
    op.alter_column('despesas_evento', 'data_vencimento', new_column_name='data')
    
    # ### end Alembic commands ### 