"""criar tabela parametros

Revision ID: criar_tabela_parametros
Revises: tornar_data_devolucao_opcional
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'criar_tabela_parametros'
down_revision = 'adicionar_campo_media_km_litro_veiculo'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parametro', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Inserir o parâmetro padrão 'gasolina'
    op.execute("""
        INSERT INTO parametro (parametro, valor, observacoes)
        VALUES ('gasolina', NULL, NULL)
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parametro')
    # ### end Alembic commands ### 