"""Add data column to ReceitaEvento

Revision ID: d2b9d9c7255e
Revises: 
Create Date: 2025-05-27 17:43:56.780075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b9d9c7255e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receita_evento', sa.Column('data', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receita_evento', 'data')
    # ### end Alembic commands ###
