name: Backup PostgreSQL to S3

on:
  schedule:
    # Executa todos os dias às 02:00 UTC (23:00 Brasília no horário padrão)
    - cron: '0 2 * * *'
    
    # 🕐 OUTROS HORÁRIOS DISPONÍVEIS (descomente o desejado):
    # - cron: '0 6 * * *'    # 06:00 UTC (03:00 Brasília)
    # - cron: '30 1 * * *'   # 01:30 UTC (22:30 Brasília)  
    # - cron: '0 2 * * 0'    # Apenas domingos às 02:00 UTC
    # - cron: '0 2 1 * *'    # Apenas dia 1 de cada mês às 02:00 UTC
    # - cron: '0 */6 * * *'  # A cada 6 horas (00:00, 06:00, 12:00, 18:00 UTC)
    # - cron: '0 3 * * 1-5'  # Segunda a sexta às 03:00 UTC (apenas dias úteis)
  
  # Permite execução manual
  workflow_dispatch:
    inputs:
      force_backup:
        description: 'Forçar backup mesmo se houver erro'
        required: false
        default: 'false'
        type: boolean

env:
  PYTHON_VERSION: '3.11'

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Instalar PostgreSQL 17 via Docker
      run: |
        # Usar PostgreSQL 17 em container para compatibilidade
        docker pull postgres:17
        
        # Criar alias para pg_dump 17
        echo '#!/bin/bash' > /tmp/pg_dump
        echo 'docker run --rm -i postgres:17 pg_dump "$@"' >> /tmp/pg_dump
        chmod +x /tmp/pg_dump
        
        # Criar alias para psql 17  
        echo '#!/bin/bash' > /tmp/psql
        echo 'docker run --rm -i postgres:17 psql "$@"' >> /tmp/psql
        chmod +x /tmp/psql
        
        # Adicionar ao PATH
        export PATH="/tmp:$PATH"
        echo "/tmp" >> $GITHUB_PATH
        
        # Verificar versão
        /tmp/pg_dump --version
        
    - name: Instalar dependências Python
      run: |
        pip install boto3 python-dotenv
        
    - name: Verificar pg_dump 17
      run: |
        pg_dump --version
        echo "PostgreSQL 17 pronto para backup!"
        
    - name: Executar backup
      env:
        # Configurações do Railway PostgreSQL
        DATABASE_URL: ${{ secrets.RAILWAY_DATABASE_URL }}
        
        # Configurações AWS S3
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BACKUP_BUCKET: ${{ secrets.S3_BACKUP_BUCKET }}
        S3_BACKUP_REGION: ${{ secrets.S3_BACKUP_REGION }}
        
        # Configurações de backup
        BACKUP_PREFIX: socrates-online
        BACKUP_RETENTION_DAYS: 30
        
      run: |
        python scripts/backup_postgres_s3.py
        
    - name: Notificar falha (opcional)
      if: failure()
      run: |
        echo "Backup falhou! Verifique os logs."
        # Aqui você pode adicionar notificação por email, Slack, etc.
        
    - name: Notificar sucesso
      if: success()
      run: |
        echo "Backup executado com sucesso!"
        # Aqui você pode adicionar notificação de sucesso se desejar
